version: '2'
services:
        lair:
                hostname: lair
                container_name: lair_lair
                build:
                        context: ./app/
                        dockerfile: Dockerfile
                ports:
                        - "11014:11014"
                restart: always
                links:
                        - lairdb
                depends_on:
                        - lairdb
                        - lairsetup
        lairapi:
                hostname: lairapi
                container_name: lair_api
                build:
                        context: ./api/
                        dockerfile: Dockerfile
                ports:
                        - "11015:11015"
                restart: always
                links:
                        - lairdb
                depends_on:
                        - lairdb
                        - lairsetup
        caddy:
                hostname: caddy
                container_name: lair_caddy
                build:
                        context: ./proxy/
                        dockerfile: Dockerfile
                links:
                        - lair
                        - lairapi
                        - lairdb
                ports:
                        - "11012-11013:11012-11013"
                depends_on:
                        - lair
                        - lairapi
                        - lairsetup
                restart: always
        ngrok:
                hostname: ngrok
                container_name: lair_ngrok
                build:
                        context: ./ngrok/
                        dockerfile: Dockerfile
                links:
                        - caddy
                volumes:
                        - ./scripts:/root/scripts
                environment:
                        HTTP_LISTENER: caddy:11012
        lairdb:
                hostname: lairdb
                container_name: lair_db
                image: mongo
                restart: always
                volumes:
                        - /usr/local/mongodb/data/db:/data/db
                ports:
                        - "27017:27017"
                entrypoint: ["/usr/bin/mongod", "--dbpath=/data/db", "--quiet", "--nounixsocket", "--replSet", "rs0", "--logpath", "/var/log/mongodb.log", "--logappend"]
        lairsetup:
                container_name: lair_setup
                image: mongo
                links:
                        - lairdb
                depends_on:
                        - lairdb
                volumes:
                        - ./scripts:/scripts
                entrypoint: '/scripts/wait-for-it.sh lairdb:27017 -- mongo lairdb:27017/admin /scripts/db_init.js'
